{
    "descriptors": [
        "and a magic wand", 
        "and a mushroom basket", 
        "and a big acorn", 
        "and an old book", 
        "and chocolate cookies",
        "and a magic amulet", 
        "with stars in their hair", 
        "and a herb basket", 
        "and a golden harp",
        "and a mushroom circle", 
        "and a golden lantern", 
        "with a silver heart",
        "and a book of spells", 
        "who sings to the moon", 
        "and a jar of fireflies",
        "with a golden flute",
        "who weaves dreams from mist", 
        "and a crown of ivy", 
        "with a patchwork cloak", 
        "who guards a hidden glade",
        "and a jar of stardust", 
        "with a living staff", 
        "who rides the northern wind", 
        "and a necklace of shells",
        "with a lute", 
        "who speaks to shadows", 
        "and a jar of moonstones", 
        "with a tarnished mirror",
        "and a wishing well", 
        "and a spool of golden thread", 
        "and a paint brush",
        "and a bowl of petals", 
        "with a crystal cup", 
        "who chases falling stars", 
        "and a map of forgotten paths",
        "with a peacock plume",
        "who knows the forest’s heart", 
        "and a bag of magic seeds", 
        "and silver bells",
        "who sleeps under a willow tree",
        "and a fairy gate", 
        "and the golden hour", 
        "and a rain storm", 
        "and the first morning frost",
        "and the dawn",
        "and a fern glen",
        "and a cozy fire",
        "and a misty morning",
        "wearing an oversized coat",
        "and a compass",
        "wearing a backpack",
        "and a tree house",
        "and a cobblestone path",
        "and a stack of books",
        "and a stack of pillows",
        "and a jar of honey",
        "and a broken mirror",
        "wearing a plaid scarf",
        "and a velvet cape",
        "with a sapphire ring",
        "who tells ancient tales",
        "and a basket of berries",
        "with a moonlit veil",
        "and a carved wooden spoon",
        "who listens to the stars",
        "and a pair of spectacles",
        "with a emerald pendant",
        "and a bundle of lavender",
        "who follows the river’s song",
        "and a tattered scroll",
        "with a brass brooch",
        "and pile of acorns",
        "who guards the twilight gate",
        "and a silver whistle",
        "with a braided cord",
        "and a clay pot",
        "who dances with the breeze",
        "and a candle light",
        "with a ruby tiara",
        "and a sack of feathers",        
        "and a woven  mat",
        "and a bed of moss",
        "who whispers to the dawn",
        "and a brass key",
        "with a silken sash",
        "and a box of secrets"
    ]
}
